"""empty message

Revision ID: fdaa03af8728
Revises: 8bc40f0fed43
Create Date: 2025-11-28 22:58:54.374366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaa03af8728'
down_revision = '8bc40f0fed43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_characters',
    sa.Column('fav_user_id', sa.Integer(), nullable=True),
    sa.Column('fav_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['fav_user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_characters')
    # ### end Alembic commands ###
